/// <summary>
/// Page Explanation Rich Text (ID 50102).
/// </summary>
page 50102 "Explanation Rich Text"
{
    PageType = StandardDialog;
    Caption = 'Explanation';

    layout
    {
        area(Content)
        {
            group(General)
            {
                group(InstructionalText)
                {
                    ShowCaption = false;
                    InstructionalText = 'The explanation of Financial Report generated by Azure OpenAI';
                }

                usercontrol(CUKHtmlAddIn; "CUK HTML AddIn")
                {
                    ApplicationArea = All;

                    trigger ControlAddInReady()
                    begin
                        CurrPage.CUKHtmlAddIn.EmbedHTML(CurrPage.Caption, ExplanationText);
                    end;
                }
            }
        }
    }

    var
        ExplanationText: Text;

    /// <summary>
    /// SetExplanationText.
    /// </summary>
    /// <param name="FromText">Text.</param>
    procedure SetExplanationText(FromText: Text)
    begin
        ExplanationText := FromText;
    end;
}